drop table if exists mpa, films, genre, genre_films, users, likes, friends cascade;

create table if not exists mpa (
  mpa_id integer generated by default as identity not null primary key,
  mpa_name varchar(20) not null
);

create table if not exists films (
  id integer generated by default as identity not null primary key,
  name varchar(255) not null,
  description varchar(1000) not null,
  release_date date not null,
  duration integer not null,
  mpa_id integer references mpa (mpa_id) on delete restrict
);

create table if not exists genre (
  id integer generated by default as identity not null primary key,
  name varchar(255) not null
);

create table if not exists genre_films (
  film_id integer references films (id) on delete cascade, 
  genre_id integer references genre (id) on delete cascade
);

create table if not exists users (
  id integer generated by default as identity not null primary key,
  email varchar(255) not null,
  login varchar(255) not null,
  name varchar(255) not null,
  birthday date not null
);

create table if not exists likes (
  film_id integer references films (id) on delete cascade,
  user_id integer references users (id) on delete cascade
);

create table if not exists friends (
  user_id integer references users (id) on delete cascade,
  friend_id integer references users (id) on delete cascade,
  status bool not null
);
